package com.treinamentos;
// Generated 22/06/2018 12:54:29 by Hibernate Tools 4.3.5.Final



/**
 * PagamentoId generated by hbm2java
 */
public class PagamentoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long cpf;
	private long cdcurso;

	public PagamentoId() {
	}

	public PagamentoId(long cpf, long cdcurso) {
		this.cpf = cpf;
		this.cdcurso = cdcurso;
	}

	public long getCpf() {
		return this.cpf;
	}

	public void setCpf(long cpf) {
		this.cpf = cpf;
	}

	public long getCdcurso() {
		return this.cdcurso;
	}

	public void setCdcurso(long cdcurso) {
		this.cdcurso = cdcurso;
	}

	
	       @Override
	       public String toString() {
	    	   
	    	   return "Pagamento [cpf= "+cpf+" cdcurso = "+cdcurso+"]";
	    	   
	    	   
	    	   
	       }
	

	

}
